SELECT  sum("CAP VALUE") AS "TotalCap",
    team_name,
    year,
    SUM(CASE WHEN POSITION = 'Quarterback' THEN "CAP VALUE" ELSE 0 END) AS "QB Cost",
    SUM(CASE WHEN POSITION = 'Cornerback' THEN "CAP VALUE" ELSE 0 END) AS "CB Cost",
    SUM(CASE WHEN POSITION = 'Defensive End' THEN "CAP VALUE" ELSE 0 END) AS "DE Cost",
    SUM(CASE WHEN POSITION = 'Defensive Tackle' THEN "CAP VALUE" ELSE 0 END) AS "DT Cost",
    SUM(CASE WHEN POSITION = 'Linebacker' THEN "CAP VALUE" ELSE 0 END) AS "LB Cost",
    SUM(CASE WHEN POSITION = 'Outside Linebacker' THEN "CAP VALUE" ELSE 0 END) AS "OLB Cost",
    SUM(CASE WHEN POSITION = 'Punter/Kicker' THEN "CAP VALUE" ELSE 0 END) AS "P/K Cost",
    SUM(CASE WHEN POSITION = 'Running Back' THEN "CAP VALUE" ELSE 0 END) AS "RB Cost",
    SUM(CASE WHEN POSITION = 'Tight End' THEN "CAP VALUE" ELSE 0 END) AS "TE Cost",
    SUM(CASE WHEN POSITION = 'Wide Receiver' THEN "CAP VALUE" ELSE 0 END) AS "WR Cost",
    SUM(CASE WHEN POSITION = 'Center' THEN "CAP VALUE" ELSE 0 END) AS "C Cost",
    SUM(CASE WHEN POSITION = 'Middle Linebacker' THEN "CAP VALUE" ELSE 0 END) AS "MLB Cost",
    SUM(CASE WHEN POSITION = 'Offensive Guard' THEN "CAP VALUE" ELSE 0 END) AS "OG Cost",
    SUM(CASE WHEN POSITION = 'Offensive Tackle' THEN "CAP VALUE" ELSE 0 END) AS "OT Cost",
    SUM(CASE WHEN POSITION = 'Long Snapper' THEN "CAP VALUE" ELSE 0 END) AS "LS Cost",
    SUM(CASE WHEN POSITION = 'Safety' THEN "CAP VALUE" ELSE 0 END) AS "S Cost",
    seasons."Wins",
    seasons."Losses",
    seasons."Ties",
    seasons."Playoffs",
    seasons."Points For",
    seasons."Points Against",
    seasons."Off Rank Pts",
    seasons."Off Rank Yds",
    seasons."Def Rank Pts",
    seasons."Def Rank Yds",
    seasons."TO Dif Rank",
    seasons."Pt Dif Rank",
    seasons."Yd Dif Rank"
FROM salaries
INNER JOIN seasons
ON salaries.team_name = seasons."Current Nickname" AND CAST(salaries.year AS NUMERIC) = seasons."Year"
GROUP BY team_name,
     year,
     seasons."Wins",
     seasons."Losses",
     seasons."Ties",
     seasons."Playoffs",
     seasons."Points For",
     seasons."Points Against",
     seasons."Off Rank Pts",
     seasons."Off Rank Yds",
     seasons."Def Rank Pts",
     seasons."Def Rank Yds",
     seasons."TO Dif Rank",
     seasons."Pt Dif Rank",
     seasons."Yd Dif Rank"
ORDER BY year DESC;
